### ISSUE TITLE
Setting pulse width when using hardware trigger from ChipWhisperer-Lite

### ISSUE THREAD

**Issue by itewqq** [newaetech/ChipSHOUTER#11]
I am using chipwhisperer and chipsohuter jointly and I would like to know how to modify the output pulse width of the chipshouter? 

I have tried to modify the `scope.glitch.repeat` parameter on the chipwhisperer side and the `cs.pulse.width` parameter on the chipshouter side, but it doesn't look like this is working from the oscilloscope.

**Comment by colinoflynn** [comment]
What widths are you testing? FYI the pulse width gets highly limited by the physical coil parameters. Page 20/21 has this graph of the [user manual](https://github.com/newaetech/ChipSHOUTER/blob/master/documentation/ChipSHOUTER%20User%20Manual.pdf) that shows the limits you can expect.

![image](https://user-images.githubusercontent.com/6100154/208175688-38c7a680-44c4-4617-8b2c-ecee74dc3f53.png)
![image](https://user-images.githubusercontent.com/6100154/208175729-ba70f440-8819-4e69-a653-8e8240f891bb.png)

> I have tried to modify the scope.glitch.repeat parameter on the chipwhisperer side and the cs.pulse.width parameter on the ?  chipshouter side

Using the mode as `glitch.output = enable_only` then modifying `repeat` should give a longer & longer input signal which translates to a longer output. Trying modifying the repeat to extremes as well (e.g., 10 vs 10000).

The `cs.pulse.width` parameter only takes effect if you call the glitch on the ChipSHOUTER API itself, the `cs.pulse.width` is ignored for the external input. The external input is a fully hardware path that basically mirrors the input on the external input (the MCX input on the ChipSHOUTER) to the MOSFET gate itself.

**Comment by itewqq** [comment]
Thanks for the fast reply!

>Using the mode as `glitch.output = enable_only` then modifying `repeat` should give a longer & longer input signal which translates to a longer output. Trying modifying the repeat to extremes as well (e.g., 10 vs 10000).

This is very important information and much appreciated. I'll give it a shot :smiling_face_with_tear:
