### ISSUE TITLE
ChipSHOUTER Python API installation in Python 3

### ISSUE THREAD

**Issue by r0b0tsp1k3** [newaetech/ChipSHOUTER#2]
On ChipWhisperer 5 vagrant VM (Python 3.6), clone the ChipSHOUTER git including "python" submodule, then try typical python3 module installation (e.g. "pip3 install <path>" or "python3 setup.py install") but always get this error when running "from chipshouter import ChipSHOUTER":

Cannot import name 'ChipSHOUTER'

Additionally, ChipSHOUTER documentation does not yet specify installation instructions beyond "install with pip install chipshouter" in parentheses ([https://chipshouter.readthedocs.io/en/latest/](url)), which does not work in Python 3.

**Comment by colinoflynn** [comment]
Closing as we now support Python3 from some time ago.
